# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1ue2PEdtdj0YKW3V1HKqkyDHfAEEvOm
"""

from flask import Flask, render_template, request
from ultralytics import YOLO
import os

app = Flask(__name__)

# Cargar modelo
model = YOLO(r"C:\Users\waltr\Downloads\mi web\model\best.pt")

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():
    if "file" not in request.files:
        return "No se envió archivo"

    file = request.files["file"]

    if file.filename == "":
        return "Archivo vacío"

    # Guardar imagen temporal
    filepath = os.path.join("static", file.filename)
    file.save(filepath)

    # Hacer predicción
    results = model(filepath)
    r = results[0]

    pred = r.names[r.probs.top1]

    return render_template("index.html", prediction=pred, image=filepath)

if __name__ == "__main__":
    app.run(debug=True)
import os

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)