# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1ue2PEdtdj0YKW3V1HKqkyDHfAEEvOm
"""

from flask import Flask, render_template, request
from ultralytics import YOLO
import os

app = Flask(__name__)

# Cargar modelo una sola vez
model = YOLO("model/best.pt")
model.to("cpu")

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():
    if "file" not in request.files:
        return "No se envió archivo"

    file = request.files["file"]

    if file.filename == "":
        return "Archivo vacío"

    os.makedirs("static", exist_ok=True)

    filename = file.filename.replace(" ", "_")
    filepath = os.path.join("static", filename)
    file.save(filepath)

    try:
        results = model(filepath)
        r = results[0]

        if r.boxes is not None and len(r.boxes) > 0:
            cls = int(r.boxes.cls[0])
            pred = r.names[cls]
        else:
            pred = "No se detectó nada"

    except Exception as e:
        return f"Error: {str(e)}"

    finally:
        # Limpieza
        if os.path.exists(filepath):
            os.remove(filepath)

    return render_template("index.html", prediction=pred)

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)